### ISSUE TITLE
如何在router-link上使用

### ISSUE THREAD

**Issue by pegziq** [l-hammer/v-track#4]
举例：
`<router-link v-trick:product.click="test"></router-link>`

**Comment by l-hammer** [comment]
官方的`router-link`组件绑定`click`事件需要添加`.native`修饰符，`v-track`暂时还不支持。可以简单描述一下需求麽？

**Comment by l-hammer** [comment]
@pegziq 官方的`router-link`组件绑定`click`事件需要添加`.native`修饰符，`v-track`暂时还不支持。可以简单描述一下需求麽？

**Comment by pegziq** [comment]
监听router-link路由的点击事件或者可以执行回调。
PS：v-track很不错的埋点插件，在项目中使用了，几乎都能满足需求，感谢作者 @l-hammer

**Comment by l-hammer** [comment]
@pegziq 我们会在下个版本支持这个特性，请持续关注，感谢使用`v-track`~

**Comment by l-hammer** [comment]
@pegziq 新版本[v.0.8.0](https://github.com/l-hammer/v-track/releases/tag/v0.8.0)已经支持组件原生click事件行为的埋点。
```vue
<router-link to="test" v-track:18015.click.native="handleNativeEvent" />
```

**Comment by pegziq** [comment]
@l-hammer good！
