### ISSUE TITLE
在部分框架的组件上无法传递参数

### ISSUE THREAD

**Issue by luckjoke** [l-hammer/v-track#47]
在ant-design-vue的a-button组件上添加click的埋点时，发现问题：可以添加函数，但函数和埋点的监听都无法收到参数，请问这个能有解决方法吗？

**Comment by l-hammer** [comment]
@luckjoke 可以提供 demo 吗？

**Comment by luckjoke** [comment]
https://codesandbox.io/s/fragrant-breeze-537qx?file=/src/App.vue

**Comment by l-hammer** [comment]
@luckjoke ant-design-vue 的 a-button 组件的 click 事件属于自定义事件，接收的[第一个参数是事件对象 event](https://github.com/vueComponent/ant-design-vue/blob/f9e823b0513782f1a1a3a5f1cc1c095435312f0b/components/button/button.tsx#L127)，并不是 comment，这里可以使用 native 修饰符监听组件原生的 click 事件。
```vue
<a-button type="primary" v-track:18015.click.native="{ clickFun, comment: '111' }"
  >ant-design-vue button</a-button
>
```
另外埋点事件这里不应该用解构。
```js
18015(context, comment, { target }) {
  console.log(comment, target);
}
```
