### ISSUE TITLE
custom.show区域展示时不兼容css3的transform的滚动操作

### ISSUE THREAD

**Issue by pegziq** [l-hammer/v-track#5]
现在移动端很多操作都是基于transform，使用custom.show区域展示时无法监听

**Comment by l-hammer** [comment]
修饰符`.custom.show`表示监听滚动容器自定义的`scroll`方法，所以需要传递滚动容器的`ref`给`v-track`来实现监听。以[cube-ui的Scroll组件](https://didi.github.io/cube-ui/#/zh-CN/docs/scroll)为例，代码如下：

```vue
<cube-scroll ref="scroll" v-track:18015.show.custom="{ ref: 'scroll' }" />
```

**Comment by pegziq** [comment]
ok啦
